spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/admin?user=admin&password=admin"
    driver-class-name: org.postgresql.Driver
    exposed:
      generate-ddl: true
  flyway:
    enabled: true
    locations:
      - classpath:/db/migration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      client-id: event-funcionario
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
